### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jmarcher** [joubertredrat/fox#4]
I suggest that you use composer.

And translate the comments to english

**Comment by joubertredrat** [comment]
Hi @jmarcher, thanks for this issue.

I'm working to provide this framework with composer create-project like. I'm looking here, what comments isn't in english? probably I forgot to translate some comments.

**Comment by jmarcher** [comment]
Index controller

**Comment by joubertredrat** [comment]
> Index controller

Fixed in 7353206e2c5a66e598a611034dfc308d9c0a4165, thanks again :+1:
