### ISSUE TITLE
A new way to concat paths

### ISSUE THREAD

**Issue by gabsprates** [joubertredrat/fox#5]
I was reading you code and i found one thing that's disturbs me.

The [lines 12 and 13](https://github.com/joubertredrat/fox/blob/master/fox/autoload.php#L12-L13) from the `autoload.php` file are an exemple of it:

```php
$composer_autoload = FOX_PATH.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vendor'.
DIRECTORY_SEPARATOR.'autoload.php';
```

That concatenation could be better...

I suggest you use the `implode` function, then you will set the `glue` (`DIRECTORY_SEPARATOR` for these cases) and the array of what you want concatenate.

If you like it, I can write the code and send a PR.

**Comment by joubertredrat** [comment]
Hi @gabsprates that's right, you're welcome to open PR with this :+1:

**Comment by gabsprates** [comment]
What is the PHP version for the current code?

**Comment by joubertredrat** [comment]
Hi @gabsprates , this framework was made using PHP 5.6, but is 7.0 ready.

**Comment by gabsprates** [comment]
All right, I'll to implement with new features.
